// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class CartDetail
{
    public int Id { get; set; }

    public int CartsId { get; set; }

    public int ProductStylesId { get; set; }

    public int Quantity { get; set; }

    public virtual ICollection<CartHistory> CartHistories { get; set; } = new List<CartHistory>();

    public virtual Cart Carts { get; set; }

    public virtual ProductStyle ProductStyles { get; set; }
}