// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class Coupon
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public int EventTypeId { get; set; }

    public DateTime? PrevTime { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string RepeatRule { get; set; }

    public byte? RepeatNum { get; set; }

    public int TargetTypeId { get; set; }

    public int? PromotionProductTypeId { get; set; }

    public string Status { get; set; }

    public int PriceThreshold { get; set; }

    public int CouponTypeId { get; set; }

    public int? DiscountQty { get; set; }

    public decimal? Amount { get; set; }

    public int? FreebieId { get; set; }

    public int? Quantity { get; set; }

    public bool ExtraSalesUsage { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime LastModified { get; set; }

    public virtual ICollection<ActivityCoupon> ActivityCoupons { get; set; } = new List<ActivityCoupon>();

    public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; } = new List<ActivityDiscount>();

    public virtual ICollection<CouponSendＭember> CouponSendＭembers { get; set; } = new List<CouponSendＭember>();

    public virtual CouponType CouponType { get; set; }

    public virtual EventType EventType { get; set; }

    public virtual Freeby Freebie { get; set; }

    public virtual ICollection<OrderUsedCoupon> OrderUsedCoupons { get; set; } = new List<OrderUsedCoupon>();

    public virtual PromotionProductType PromotionProductType { get; set; }

    public virtual TargetType TargetType { get; set; }

    public virtual ICollection<MemberLevel> MemberLevels { get; set; } = new List<MemberLevel>();

    public virtual ICollection<MemberTag> MemberTags { get; set; } = new List<MemberTag>();

    public virtual ICollection<ProductTag> ProductTags { get; set; } = new List<ProductTag>();

    public virtual ICollection<ThirdCategory> ThirdCategories { get; set; } = new List<ThirdCategory>();
}