// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class Dm
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string MailContent { get; set; }

    public string Dmfile { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? SendingTime { get; set; }
}