// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class MemberTag
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreateAt { get; set; }

    public string Description { get; set; }

    public virtual ICollection<MemberTagCondition> MemberTagConditions { get; set; } = new List<MemberTagCondition>();

    public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; } = new List<ActivityDiscount>();

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}