// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class MemberLevel
{
    public int Id { get; set; }

    public int LevelOrder { get; set; }

    public string Name { get; set; }

    public int UpgradePrice { get; set; }

    public int UpgradeOrderCount { get; set; }

    public int TimePeriod { get; set; }

    public decimal GainPointRate { get; set; }

    public string Description { get; set; }

    public string LevelName { get; set; }

    public virtual ICollection<MemberLevelDetail> MemberLevelDetails { get; set; } = new List<MemberLevelDetail>();

    public virtual ICollection<MemberLevelDetailsHistory> MemberLevelDetailsHistories { get; set; } = new List<MemberLevelDetailsHistory>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; } = new List<ActivityDiscount>();

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();
}