// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class Member
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Nickname { get; set; }

    public int MemberLevelId { get; set; }

    public int Points { get; set; }

    public string Thumbnail { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public DateTime Birthday { get; set; }

    public string PhoneNumber { get; set; }

    public bool Dmsubscribe { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime LastModified { get; set; }

    public bool IsConfirm { get; set; }

    public bool IsBanned { get; set; }

    public string ConfirmCode { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual ICollection<CouponSendＭember> CouponSendＭembers { get; set; } = new List<CouponSendＭember>();

    public virtual ICollection<ExperienceEnrollment> ExperienceEnrollments { get; set; } = new List<ExperienceEnrollment>();

    public virtual MemberLevel MemberLevel { get; set; }

    public virtual MemberLevelDetail MemberLevelDetail { get; set; }

    public virtual ICollection<MemberPoint> MemberPoints { get; set; } = new List<MemberPoint>();

    public virtual ICollection<MembersHistory> MembersHistories { get; set; } = new List<MembersHistory>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<SkillEnrollment> SkillEnrollments { get; set; } = new List<SkillEnrollment>();

    public virtual ICollection<MemberTag> MemberTags { get; set; } = new List<MemberTag>();
}