// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Snapshot { get; set; }

    public string RecipientName { get; set; }

    public string RecipientPhone { get; set; }

    public string RecipientAddress { get; set; }

    public int OrderStatusId { get; set; }

    public DateTime CreateAt { get; set; }

    public string Note { get; set; }

    public int TotalProductsPrice { get; set; }

    public int DeliverPrice { get; set; }

    public int DiscountPrice { get; set; }

    public int UsedPoint { get; set; }

    public string RecipientEmail { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<MemberPoint> MemberPoints { get; set; } = new List<MemberPoint>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderReturnDetail> OrderReturnDetails { get; set; } = new List<OrderReturnDetail>();

    public virtual OrderStatus OrderStatus { get; set; }

    public virtual ICollection<OrderUsedCoupon> OrderUsedCoupons { get; set; } = new List<OrderUsedCoupon>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<ProductComment> ProductComments { get; set; } = new List<ProductComment>();
}