// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DapperPractice1.Models;

public partial class SecondCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int FirstCategoryId { get; set; }

    public virtual FirstCategory FirstCategory { get; set; }

    public virtual ICollection<ThirdCategory> ThirdCategories { get; set; } = new List<ThirdCategory>();
}